runtime: nodejs16
service: cinematheque-back
handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/cinematheque-back/\1
    upload: dist/cinematheque-back/(.*)(|\.map)
  - url: /(.*)
    static_files: dist/cinematheque-back/index.js
    upload: dist/cinematheque-back/index.js
